language: node_js
node_js:
- "stable"
cache:
  directories:
    - "node_modules"
    - npm i nyc --save-dev
    - npm install codeclimate-test-reporter istanbul -g
after_success:
  - npm run coveralls