language: node_js
node_js:
- "stable"
cache:
  directories:
    - "node_modules"
    - npm i nyc --save-dev
    - npm install codeclimate-test-reporter istanbul -g
addons:
    code_climate:
        repo_token: f9024d219adc13a6b19339498a1bac37841f2a079a021a952549b02bc6f9e1eb
script:
    - npm run coveralls
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info