language: node_js
node_js:
 - "stable"

cache:
  directories:
    - "node_modules"
    - npm i nyc --save-dev

addons:
    code_climate:
        repo_token: f9024d219adc13a6b19339498a1bac37841f2a079a021a952549b02bc6f9e1eb

after_success: npm run coverage
