language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
  - npm i nyc --save-dev
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info